{
 "title": "Twitch Realtime",
 "time": { "from": "2025-06-04T10:50:00.000Z", "to": "2025-06-04T11:09:00.000Z" },
 "templating": {
  "list": [
   { "name": "selected_game" }
  ]
 },
 "panels": [
  {
   "title": "Total Current Viewers",
   "type": "stat",
   "gridPos": { "h": 6, "w": 11, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "WITH current_stream_snapshot AS (\r\n    SELECT \r\n        stream_id,\r\n        argMax(viewer_count, data_retrieved_at) as latest_viewer_count,\r\n        argMax(stream_type, data_retrieved_at) as latest_stream_type\r\n    FROM default.game_streams_enriched\r\n    WHERE data_retrieved_at >= now() - INTERVAL 5 MINUTE\r\n    GROUP BY stream_id\r\n    HAVING latest_stream_type = 'live'\r\n)\r\nSELECT sum(ifNull(latest_viewer_count, 0)) as total_viewers\r\nFROM current_stream_snapshot"
    }
   ]
  },
  {
   "title": "Top Games by Total Viewers",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 13, "x": 11, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT \r\n    toStartOfInterval(data_retrieved_at, INTERVAL 1 MINUTE) as time,\r\n    sum(ifNull(viewer_count, 0)) as total_viewers\r\nFROM default.game_streams_enriched\r\nWHERE data_retrieved_at >= toTimeZone(now(), 'Asia/Ho_Chi_Minh') - INTERVAL 10 MINUTE\r\n    AND stream_type = 'live'\r\n    AND game_name IS NOT NULL\r\nGROUP BY time\r\nORDER BY time desc\r\nLIMIT 15;"
    }
   ]
  },
  {
   "title": "Top Streamer",
   "type": "table",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 6 },
   "targets": [
    {
     "rawSql": "WITH current_stream_snapshot AS (\r\n    SELECT \r\n        stream_id,\r\n        argMax(user_name, data_retrieved_at) as latest_user_name,\r\n        argMax(game_name, data_retrieved_at) as latest_game_name,\r\n        argMax(viewer_count, data_retrieved_at) as latest_viewer_count,\r\n        argMax(title, data_retrieved_at) as latest_title,\r\n        argMax(stream_type, data_retrieved_at) as latest_stream_type\r\n    FROM default.game_streams_enriched\r\n    WHERE data_retrieved_at >= now() - INTERVAL 5 MINUTE\r\n    GROUP BY stream_id\r\n)\r\nSELECT \r\n    ifNull(latest_user_name, 'Unknown') as streamer,\r\n    ifNull(latest_game_name, 'Unknown') as game,\r\n    ifNull(latest_viewer_count, 0) as viewers,\r\n    substr(ifNull(latest_title, ''), 1, 50) as title_preview\r\nFROM current_stream_snapshot\r\nWHERE latest_user_name IS NOT NULL\r\nORDER BY latest_viewer_count DESC\r\nLIMIT 20"
    }
   ]
  },
  {
   "title": "Top Games by Total Viewers",
   "type": "barchart",
   "gridPos": { "h": 10, "w": 13, "x": 11, "y": 9 },
   "targets": [
    {
     "rawSql": "WITH current_stream_snapshot AS (\r\n    SELECT \r\n        stream_id,\r\n        argMax(game_name, data_retrieved_at) as latest_game_name,\r\n        argMax(viewer_count, data_retrieved_at) as latest_viewer_count,\r\n        argMax(stream_type, data_retrieved_at) as latest_stream_type\r\n    FROM default.game_streams_enriched\r\n    WHERE data_retrieved_at >= now() - INTERVAL 5 MINUTE\r\n    GROUP BY stream_id\r\n)\r\nSELECT \r\n    ifNull(latest_game_name, 'Unknown') as game_name,\r\n    sum(ifNull(latest_viewer_count, 0)) as total_viewers\r\nFROM current_stream_snapshot\r\nWHERE latest_game_name IS NOT NULL\r\nGROUP BY latest_game_name\r\nORDER BY total_viewers DESC\r\nLIMIT 5"
    }
   ]
  },
  {
   "title": "Most Popular Tags",
   "type": "barchart",
   "gridPos": { "h": 14, "w": 11, "x": 0, "y": 13 },
   "targets": [
    {
     "rawSql": "WITH current_stream_snapshot AS (\r\n    SELECT \r\n        stream_id,\r\n        argMax(tags, data_retrieved_at) as latest_tags,\r\n        argMax(stream_type, data_retrieved_at) as latest_stream_type\r\n    FROM default.game_streams_enriched\r\n    WHERE data_retrieved_at >= now() - INTERVAL 10 MINUTE\r\n    GROUP BY stream_id\r\n    HAVING latest_stream_type = 'live' \r\n), \r\nfiltered_tags AS (\r\n    SELECT \r\n        assumeNotNull(latest_tags) as tags_string\r\n    FROM current_stream_snapshot\r\n    WHERE latest_tags IS NOT NULL \r\n        AND latest_tags != ''\r\n        AND latest_tags != 'null'\r\n),\r\ntag_split AS (\r\n    SELECT \r\n        trimBoth(arrayJoin(splitByChar(',', tags_string))) as tag\r\n    FROM filtered_tags\r\n)\r\nSELECT \r\n    tag,\r\n    count() as tag_count\r\nFROM tag_split\r\nWHERE tag != '' AND tag IS NOT NULL\r\nGROUP BY tag\r\nORDER BY tag_count DESC\r\nLIMIT 10"
    }
   ]
  },
  {
   "title": "Stream Distribution by Language",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 13, "x": 11, "y": 19 },
   "targets": [
    {
     "rawSql": "WITH current_stream_snapshot AS (\r\n    SELECT \r\n        stream_id,\r\n        argMax(language, data_retrieved_at) as latest_language,\r\n        argMax(stream_type, data_retrieved_at) as latest_stream_type\r\n    FROM default.game_streams_enriched\r\n    WHERE data_retrieved_at >= now() - INTERVAL 5 MINUTE\r\n    GROUP BY stream_id\r\n)\r\nSELECT \r\n    ifNull(latest_language, 'Unknown') as language,\r\n    count() as stream_count\r\nFROM current_stream_snapshot\r\nGROUP BY latest_language\r\nORDER BY stream_count DESC\r\nLIMIT 10"
    }
   ]
  }
 ]
}